trigger:
- master

pool:
  vmImage: windows-latest

name: $(Year:yy)$(DayOfYear)$(Rev:r)
steps:
- task: UseDotNet@2
  displayName: Ensure 3.1 SDK
  inputs:
    version: 3.1.x
    performMultiLevelLookup: true

- task: UseDotNet@2
  displayName: Ensure 2.1 Runtime
  inputs:
    packageType: runtime
    version: 2.1.x
    performMultiLevelLookup: true

- script: dotnet build src\Blake2Fast -c Dist --version-suffix ci$(Build.BuildNumber)
  displayName: Build

- script: dotnet test tests\Blake2.Test -c Release -s tests\runsettings --logger trx
  displayName: Test

- script: dotnet test tests\Blake2.Test -c Release -f netcoreapp3.0 -s tests\runsettings --logger trx
  displayName: Test - No AVX
  env:
    COMPlus_EnableAVX: 0

- task: NuGetAuthenticate@0
  condition: ne(variables['Build.Reason'], 'PullRequest')

- script: dotnet nuget push --api-key AzureArtifacts --source https://pkgs.dev.azure.com/saucecontrol/Blake2Fast/_packaging/blake2fast_ci/nuget/v3/index.json out\bin\Blake2Fast\Dist\SauceControl.Blake2Fast.*.nupkg
  displayName: Push
  condition: ne(variables['Build.Reason'], 'PullRequest')

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: out\testresults\*.trx
